# Generated by Django 5.1 on 2024-08-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('turkish', models.CharField(max_length=100)),
                ('maths', models.CharField(max_length=100)),
                ('social_sciences', models.CharField(max_length=100)),
                ('fen_sciences', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Answers',
                'db_table': 'Answers',
            },
        ),
    ]
