# Generated by Django 5.1 on 2024-08-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_answer_options_alter_answer_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='book_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='exam_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='name',
            field=models.CharField(default='BilgiSarmak', max_length=200),
            preserve_default=False,
        ),
    ]
