# Generated by Django 5.1 on 2024-08-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_answer_book_type_answer_exam_type_answer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
